#!/usr/bin/env racket
#lang racket/base

(require
  racket/cmdline
  racket/function
  racket/string
  "assembler/assembler.rkt"
  "assembler/s-record.rkt"
  "emulator/emulator.rkt"
  "op-table.rkt"
  "utils.rkt"
  "machines/ril011w.rkt"
  command-tree)

(current-op-table (call-with-input-file "mpus/6802.tab"
                    (lambda (in) (read in))))

(define (assemble-to-binary filepath)
  (display (assemble filepath)))

(define (assemble-to-hex filepath)
  (displayln
    (string-join
      (map (curry format-hex)
           (bytes->list (assemble filepath))))))

(define (assemble-to-s-record filepath [header #f])
  (bytes->s-record (assemble filepath)
                   #:header header))

(command-tree
  `([assemble (to-binary ,assemble-to-binary)
              (to-hex ,assemble-to-hex)
              (to-s-record ,assemble-to-s-record)]
    [emulate  ,(lambda (kernel)
                 (emulate kernel ril011w-address-decode))])
  (current-command-line-arguments))
